# This builds a Docker image
name: Build Docker image

# manually triggered only
on: [ workflow_dispatch ]

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build SLATE with GNU & generic blas
        env:
          tag: slate:gnu
          dir: devtools/Docker_GNU
        run: |
          docker build --tag stenczelt/$tag $dir
          docker push stenczelt/$tag

      - name: Build SLATE with GNU & MKL
        env:
          tag: slate:mkl-gnu
          dir: devtools/Docker_GNU_MKL
        run: |
          docker build --tag stenczelt/$tag $dir
          docker push stenczelt/$tag

      - name: Build SLATE with Intel Compilers
        env:
          tag: slate:intel
          dir: devtools/Docker_ifort
        run: |
          docker build --tag stenczelt/$tag $dir
          docker push stenczelt/$tag
