# This builds a Docker image
name: Build Docker image

# manually triggered only
on: [ workflow_dispatch ]

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build SLATE with GNU & generic blas
        run: |
          docker build --tag stenczelt/slate:gnu devtools/Docker_GNU
          docker push stenczelt/slate:gnu

#      - name: Build SLATE with MKL/GNU
#        run: |
#          docker build --tag stenczelt/slate:mkl-gnu devtools/Docker_GNU_MKL
#          docker push stenczelt/slate:mkl-gnu
